### PR TITLE
Keyrage/fix 156

### PR DESCRIPTION
**Pull request by keyrage**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by EasyAsABC123** [comment]
@keyrage just need you to sign the CLA! :+1:

**Comment by keyrage** [comment]
It's a small fix and I'm not a developer so I'm not expecting to be contributing much on the code side. Thinking about putting together a test suite for the cookbook though.

**Comment by EasyAsABC123** [comment]
If you'd prefer I can make the change tomorrow, but everyone is a developer.  And chef is a community you'll never find a true chef not willing to talk about it or help his fellow chefs.  

Let me know :)

**Comment by ksubrama** [comment]
I've become aware of the http://docs.chef.io/community_contributions.html#the-obvious-fix-rule and this seems small enough to qualify.  I'm going to merge it in given that.

**Pull request merged**
