### PR TITLE
raised the level of .rubocop.yml

### PR DESCRIPTION
**Pull request by EasyAsABC123**
@ksubrama just learned about this might as well implement it.

### CODE REVIEW

**Comment by ksubrama** [comment]
I'm back from vacation!  Sorry for the delay.

**Comment by EasyAsABC123** [comment]
@ksubrama nice! hope it was an awesome one.

**Comment by keyrage** [comment]
This change looks to have broken the cookbook. config.rb has a chnage in line 30 where the shell_out syntax has changed. This breaks chef runs in chef 12.01 (And probably ther versions but this is the verison I'm using"

"NameError: No resource, method, or local variable named returns' forChef::Provider::IisPool"

"shell_out!(cmd, returns: new_resource.returns)" should be "shell_out!(cmd, :returns => new_resource.returns)"

**Comment by EasyAsABC123** [comment]
Thank you for finding this!!!

Justin Schuhmann

**Comment by keyrage** [comment]
No worries, first time even looking at Ruby code so quite pleased I could follow the code and find it..

**Comment by EasyAsABC123** [comment]
Time to be a contributor! Download the GitHub app and fork this repo, make the change commit it and push it up! Then make pull request.

Justin Schuhmann

**Comment by keyrage** [comment]
Should I raise an issue for syntax error to track against the commit?

**Comment by EasyAsABC123** [comment]
Exactly! Then I'll look at it and try to test it then accept it!

Justin Schuhmann

**Pull request merged**
