### PR TITLE
Apppool properties

### PR DESCRIPTION
**Pull request by Annih**
Jira : https://tickets.opscode.com/browse/COOK-4684
I updated the pool request from ProTip (https://github.com/opscode-cookbooks/iis/pull/41) to ad README update and some ruby cleanup.

### CODE REVIEW

**Comment by ksubrama** [comment]
Thanks for the cleanup @Annih .  I still feel a bit uncomfortable about passing arbitrary apppool properties through without checking them against the ones already defined.  what if a default somewhere respecifies a property that is explicitly handled as an attribute and someone tries to override the attribute but instead finds that their changes aren't taking effect.

Furthermore, the way we currently shell out, if a hash is provided and any single value in that has has & or ^ or % or something that we think might be a shell metacharacter, the apppool command is run through cmd /c which would throw of the escaping for all the other values.  It's generally inviting quite a bit of pain.

For now, if there are specific properties you want to add, add them as attributes.  I'll need to think a bit more about how best to handle arbitrary passthrough.

**Comment by nwesoccer** [comment]
@ksubrama There are a couple of pull request open/closed-without-merge that all seem to have been created out of the necessity for more properties being set.  We are actually having the same issue.  There are several settings on the app pool that we need to set that are not currently supported by this recipe.  Have you been able to put additional thought to this.  I agree I don't think arbitrary passthrough is the right way, but I also don't want to maintain a separate fork just to add more property attributes.  I also don't like the idea of using the iis_config provider because that would not provide idempotence.  How hard would it be to support all possible properties?  Or maybe somehow allowing for a dynamic property/command definition.

Side note: I also like the idempotence/check that was added to pool.rb using is_new_value etc.

**Comment by EasyAsABC123** [comment]
@nwesoccer can you give me a list of all the settings you want to be able to set on an app pool?  I'll put them all into official support, also thanks I was happy to write all the iis code that gained everyone idempotence.  It was something we were using and we are all about sharing.

**Comment by nwesoccer** [comment]
@EasyAsABC123 Sure thing. The following are the properties we change from their default.  The ones I have in bold are the ones that I don't believe are currently supported by the recipe.  I generated this list using: appcmd list apppool /apppool.name:NAME -text:* and narrowed it down to only the ones IIS shows as modified from the defaults (bolded).
Ideally we'd be able to set any of the properties that this command lists.

Thanks!

* [add]
 * **startMode**
 * [processModel]
   * identityType
    * userName
    * password
    * **loadUserProfile**
    * idleTimeout
  * [recycling]
    * **disallowRotationOnConfigChange**
    * logEventOnRecycle
    * [periodicRestart]
      * time
      * [schedule]
        * [add]
          * value

**Comment by EasyAsABC123** [comment]
@nwesoccer Opened a new one for you https://github.com/opscode-cookbooks/iis/pull/123, it adds full support for the items mentioned above.  Feel free to test and make sure you are satisfied.

https://github.com/EasyAsABC123/iis/tree/feature-iis_pool_properties

**Comment by ksubrama** [comment]
Closing this - #123 should contain the properties you needed.

**Pull request closed without merging**
