### PR TITLE
Win32 include only on Windows

### PR DESCRIPTION
**Pull request by olivierlemasle**
Fix win32/registry import (was breaking on Linux platform on branch enhancement-iis_version_detection, due to the fix to #185)

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
Why is the IIS cookbook running on Linux? I'm just curious

Justin Schuhmann

**Comment by olivierlemasle** [comment]
Hi Justin,

I recognize it may sound curious.
I use Chef Solo as a Vagrant provisioner, in a multi-machines setup.

In fact, I provision an application which requires:
- a Linux VM (for database + deamon)
- a Windows VM (for the ASP.NET web application)

Because they're two parts of the same application, I've been creating a single cookbook, with two recipes. Therefore, "iis" is a dependency for my cookbook, as well as linux-specific cookbooks.

I use Berkshelf (and the Vagrant Berkshelf plugin) to manage dependencies and push them in the vagrant machines. The Vagrant Berkshelf plugin install all dependencies for both machines.

With the updated "iis" cookbook, I have an error (due to the absence of win32/registry in Linux), that did not occur before (and which is fixed with this commit). The "iis" cookbook is not _used_ on my Linux machine, but it is loaded, and this is sufficient to cause the error.

Other Windows-only cookbooks like  "windows" or "powershell" do not cause any error, because their windows-specific imports are always enabled only on Windows platform.

Examples:
- https://github.com/opscode-cookbooks/windows/blob/9a9ee67e5a5ac55a75c2f047f870542d6a39184f/libraries/registry_helper.rb#L26
- https://github.com/opscode-cookbooks/powershell/blob/89b8f09eb2557957618f4f1e47cb8e3c331e2374/recipes/powershell4.rb#L25

**Comment by EasyAsABC123** [comment]
In your wrapper cookbook can you not simply wrap it in the if platform ==windows?  I feel that might be a cleaner solution

Justin Schuhmann

**Comment by btm** [comment]
@EasyAsABC123 This is a common problem because cookbook dependencies in the cookbook metadata don't take a platform argument. The cookbook gets pulled down on other platforms and the ruby gets evaluated because its a dependency, even though the code is never used.

When it gets written, I think [eager_load_libraries](https://github.com/chef/chef-rfc/blob/master/rfc040-on-demand-cookbook-libraries.md) could be used instead to prevent libraries from being loaded, but some day we will just improve cookbook metadata to handle this case. https://tickets.opscode.com/browse/CHEF-3282.

**Comment by EasyAsABC123** [comment]
@olivierlemasle sorry about that, I don't think I fully understood the issue.  Now that I've read @btm comment I realize the issue.  Please use his recommendation of `eager_load_libraries` in your cookbook to solve this issue.  In the future it looks like you'll be able to pass the depends and platform.  When this happens you would be able to say

```ruby
depends iis(platform=='windows')
```

but for the time being you'll need to add

```ruby
depends iis
eager_load_libraries false
```

Sorry again for the misunderstanding, I have little experience with berkshelf (i'll have to rectify that when my new macbook gets here)

**Comment by btm** [comment]
@EasyAsABC123 Well, I don't think @jkeiser has started work on implementing RFC040 yet. I don't see any code in master or pull requests. @olivierlemasle's patch is the correct pattern for now. 

You can see where we do the same thing for any win32 libraries in other cookbooks:
https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb#L5
https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_helper.rb#L21

**Comment by EasyAsABC123** [comment]
whoops, didn't read that far since I was at work (they block github).  

Looking over this change and what is already in the IIS master branch for the same reason.

Thanks @olivierlemasle for the change, and @btm for the wisdom

**Comment by olivierlemasle** [comment]
Thanks @EasyAsABC123  and @btm !

**Pull request merged**
