### PR TITLE
Adds a gitter channel

### PR DESCRIPTION
**Pull request by spuder**
This adds the ability to chat about a specific cookbook inside of a gitter channel. This could be very beneficial for long running issues that have a lot of back and forth like the following:

https://github.com/opscode-cookbooks/iis/issues/145 

While there is an IRC, the conversations are not recorded, and you don't have the option of receiving notifications when a new commit happens. 

Understandably, offering a chat might not be something that you want to do. If so, I'm not offended if you reject this merge request.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @spuder

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by btm** [comment]
FYI, the IRC channels are logged and searchable via botbot:

https://botbot.me/freenode/chef/
https://botbot.me/freenode/chef-hacking/

**Comment by EasyAsABC123** [comment]
@spuder closing, as @btm stated this an enhancement.

**Pull request closed without merging**
